version: 0.2

phases:
  install:
    commands:
      - # yum update -y
  pre_build:
    commands:
      - mkdir -p artifacts
  build:
    commands:
      - mkdir -p lambda/layers/photo-deps/python
      - pip install --target lambda/layers/photo-deps/python Pillow
      - pip install --target lambda/layers/photo-deps/python numpy
      - pip install --target lambda/layers/photo-deps/python boto3
      - pushd lambda/layers/photo-deps && zip -r ../../../artifacts/photo-deps.zip . && popd
  post_build:
    commands:
      - aws s3 cp artifacts/photo-deps.zip s3://nbachmei.personal/artifacts/photo-deps.zip      
