version: 0.2

phases:
  install:
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mkdir -p lambda/layers/photo-deps/python
      - pip install --target lambda/layers/photo-deps/python -r lambda/yelp-photo-resize/requirements.txt      
  post_build:
    commands:
      - cd cdk
      - cdk synth
