version: 0.2

phases:
  install:
    commands:
      - apt-get -y update && apt-get -y install npm zip git
      - npm install -g aws-cdk
  pre_build:
    commands:
      - pip install -r cdk/requirements.txt
  build:
    commands:
      - cd cdk
      - cdk synth
  post_build:
    commands:
      - echo post
