version: 0.2

phases:
  install:
    commands:
      - #apt-get -y update && apt-get -y install npm zip git
      - #npm install -g aws-cdk
  pre_build:
    commands:
      - #pip install -r cdk/requirements.txt
  build:
    commands:
      - mkdir -p lambda/layers/photo-deps/python
      - pip install --target lambda/layers/photo-deps/python -r lambda/yelp-photo-resize/requirements.txt      
  post_build:
    commands:
      - cd cdk
      - cdk synth
